[global]
showErrorDetails = "none"

[client]
showErrorDetails = "none"
showSidebarNavigation = false

[runner]
magicEnabled = true
fastReruns = true

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
